print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/kiyotatoru/Documents/Home/Unity/beaver_room/beaver_room/Assets/Resouces/level_01_village.mb"`)
{		
	file -o "/Users/kiyotatoru/Documents/Home/Unity/beaver_room/beaver_room/Assets/Resouces/level_01_village.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/kiyotatoru/Documents/Home/Unity/beaver_room/beaver_room/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/kiyotatoru/Documents/Home/Unity/beaver_room/beaver_room/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/kiyotatoru/Documents/Home/Unity/beaver_room/beaver_room/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
